export * from "./about";
export * from "./admin-panel";
export * from "./home";
export * from "./login";
export * from "./news";
export * from "./page-404";
export * from "./register";
export * from "./service";
export * from "./profile";
